### ISSUE TITLE
Client crashes when searching agricraft stuff

### ISSUE THREAD

**Issue by Cuplex17** [scalda/FoolCraft#429] opened 2017-05-02 05:32 UTC
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
The client side crashes when searching @agricraft in JEI or scrolling to the 5th page on the large gui scale in video settings. This only happens on multiplayer.

## Reproduce Steps
1. Join a server using the latest version of Foolcraft.
2. Open JEI.
3.Search @agricraft.

## Additional Information
Crash report: https://pastebin.com/fB8xPHqa

The issue can be temporarily fixed by changing the JEI config file "itemBlacklist" and hiding all agricraft items.

**Comment by legodude17** [comment] 2017-05-02 19:27
Duplicate of #409.

**Closed** 2017-06-08 08:17 UTC
