### ISSUE TITLE
Fatally Missing Blocks and Items

### ISSUE THREAD

**Issue by gardner315** [scalda/FoolCraft#266] opened 2017-04-14 04:04 UTC
## SUGGESTION/HELP
- [] I would like to propose an additional mod, config change, custom recipe, etc.
- [] I am requesting help with installing or running the pack

**Comment by Jo-Mamma75** [comment] 2017-04-14 04:19
Duplicate of #211 
You apparently didn't search very hard for previously reported issues.
It has to do with the version of of the pack on your computer and the version on the server are different.

**Closed by Jo-Mamma75** 2017-04-14 04:19 UTC
Labels: duplicate

**Comment by gardner315** [comment] 2017-04-14 04:20
@Jo-Mamma75  i found that but i did not work.
