### ISSUE TITLE
When i logged to my world it crash

### ISSUE THREAD

**Issue by fabri2000779** [scalda/FoolCraft#375] opened 2017-04-25 16:02 UTC
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
when i logged to my world it crashed by ticking world 

## Reproduce Steps
just update to the last version and use a map of a older version you can reproduce this error

## Additional Information
https://github.com/scalda/FoolCraft/issues/357#issuecomment-297075928
the crash report:
[crash-2017-04-25_01.43.51-server.txt](https://github.com/scalda/FoolCraft/files/955660/crash-2017-04-25_01.43.51-server.txt)
 I tried using mcedit, but all I am seeing is pink blocks with question marks. And my fluid cows are not there. What should I do to get past that?

**Comment by legodude17** [comment] 2017-04-26 20:20
Duplicate of #357.

**Comment by fabri2000779** [comment] 2017-04-26 20:28
@legodude17 well if someone help in that ticket we probably dont open another one but here we are

**Comment by legodude17** [comment] 2017-04-26 21:40
@fabri2000779 Don't open a new ticket just because you are impatient, that is immature.

**Comment by fabri2000779** [comment] 2017-04-26 21:45
Nice guys you win, worst dev team and worst support, good luck with your modpack

**Comment by Morphosiz** [comment] 2017-04-27 02:50
Impatient? I am sorry, did you just say that we are impatient when we waited 2 days for a reply and nothing came out of it and we are impatient, how nice.

**Comment by Morphosiz** [comment] 2017-04-27 02:52
are you even part of the dev team in the first place?

**Comment by Morphosiz** [comment] 2017-04-27 03:07
anyways, @fabri2000779, just wait for the dev team to reply. I realised that they went off the radar for sometime, they are probably testing stuff out.

**Comment by fabri2000779** [comment] 2017-04-27 03:12
@Morphosiz hope so and sorry about you ticket man

**Comment by Morphosiz** [comment] 2017-04-27 03:18
@fabri2000779 don't worry about it, I appreciate that you tried to help. How is your server? Is it up?

**Comment by fabri2000779** [comment] 2017-04-27 03:22
yeah all good, i reset the foolcraft server map so the problem has been resolve and the people are playing so all good and my other 3 server are pretty stable so my community is going like i want

**Comment by Morphosiz** [comment] 2017-04-27 03:33
that's good. mine still doesn't work

**Comment by fabri2000779** [comment] 2017-04-27 03:49
:( well if you wanna play online man you are welcome on my community

**Comment by Morphosiz** [comment] 2017-04-27 04:05
hey, that sounds really good man, how do I go about doing that?

**Comment by fabri2000779** [comment] 2017-04-27 04:06
@Morphosiz go here https://discord.gg/UhZAXHf follow the application process and i will whitelist you

**Closed** 2017-05-03 15:14 UTC
