### ISSUE TITLE
Iskallum Reactor/Thermal Dynamics causing world crash

### ISSUE THREAD

**Issue by dxn000** [scalda/FoolCraft#290] opened 2017-04-17 12:43 UTC
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description
World crashing after placing Thermal Dynamics Energy cell (fully upgraded) onto the Iskallum Reactor power tap. Have included the crash report below. Server will restart but will crash if chunk is loaded. Will go into MCEdit to remove entity

## Reproduce Steps
[crash-2017-04-17_08.31.01-server.txt](https://github.com/scalda/FoolCraft/files/925546/crash-2017-04-17_08.31.01-server.txt)

**Comment by legodude17** [comment] 2017-04-17 16:47
Ref zairus/IskalliumReactors#7

**Comment by WinterGrave** [comment] 2017-04-17 16:52
Thank you, I take the issue to work on it as soon as I have a proper equipment to get me back on coding.

**Comment by legodude17** [comment] 2017-04-17 17:13
@WinterGrave Ok, hope your find some good equipment! Thanks for the great mod!

**Comment by Jo-Mamma75** [comment] 2017-04-17 21:28
Duplicate of #207

**Closed by Jo-Mamma75** 2017-04-17 21:28 UTC
Labels: bug, duplicate
