### ISSUE TITLE
FC 2.5.1 Weirding Gadgit not working properly

### ISSUE THREAD

**Issue by johnwolf01** [scalda/FoolCraft#867] opened 2017-11-21 12:14 UTC
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I'm using the Weirding Gadget as suggested,  but it connect and disconnect repeatedly.

- Situation
Home base Location The End. 
Im using one Weirding Gadget Right underneath my Bulk Storage ( Colossal Chest ) where items are sent 1st when crafting, resource gathering, exct. - from this chest it is sent to drawers. 
The 2nd Weirding Gatget is located at my main ME systems ( crafters Wireless exct.)

- When Roaming the Overworld or nether I often get the message "no power" or just a empty "wireless crafting Terminal" even though both have sufficient power. When the above happen and I sometimes 
re-open the Wireless Crafting Terminal and it suddenly reconnected and you can see that the items being read from the various storage get added as the system "re-power". 

- My conclusion for this is that the Weirding gadget has some temporary error where it does not keep the chunks loaded where the above mentioned systems are in place. I can not prove it but I fear it may yet again lead to item losses. As the system works intermittently. Connecting and disconnecting.
 I often find the Weirding gadget not spinning 2-3 times per day while playing, and I click on it to activate it every time I go  to a different dimension, and find it tedious. 

## Additional Information

http://prntscr.com/hdasea (World Map Base Reference)

http://prntscr.com/hdanh0 1st Location as mentioned (note in minimap for refrence to World Map)

http://prntscr.com/hdaow9 2nd Location as mentioned

**Comment by BrisingrAerowing** [comment] 2017-11-29 01:57
This (and a number of other crashes) appear to be caused by The Weirding Gadget. I think that mod is not exactly stable on 1.10.2.

**Comment by scalda** [comment] 2018-01-08 15:30
not heard anything here for 27 days so will be closing

**Closed by scalda** 2018-01-08 15:30 UTC
