### ISSUE TITLE
Astral Sorcery marble can no longer be chiseled

### ISSUE THREAD

**Issue by Chachava** [scalda/FoolCraft#853] opened 2017-11-10 20:49 UTC
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

Before the most recent update I was able to chisel the astral sorcery marble into chisel variants, since the update I no longer can. 

Place Astral Sorcery marble in any chisel.

**Comment by BrisingrAerowing** [comment] 2017-11-12 06:24
This was caused by the removal of OreDict variants from Chisel (apparently it was rather buggy). ModTweaker for 1.10.2 has Chisel support, so adding the following to one of the scripts should work:

```text
# At the top of the file
import mods.chisel.Groups; 

# Somewhere else
Groups.addVariation("marble", <astralsorcery:BlockMarble>);
'''

I did this in my custom pack (using modified FC scripts and config).

**Comment by Chachava** [comment] 2017-11-12 19:43
Thank you for the reply, I'll give that a try

**Comment by johnwolf01** [comment] 2017-11-17 10:35
@scalda 
Same applies to Quite Clear glass.
you can no longer chisel Vanilla glass into Quite Clear Glass.
you have to smelt vanilla glass in alloy smelter, or melt it and cast it in Tinkers.

**Comment by scalda** [comment] 2017-12-11 11:08
this will be in 2.6 out today

**Closed by scalda** 2017-12-11 11:08 UTC
Labels: Fixed in a pack update
