### ISSUE TITLE
Can't climb up Chisels & Bits stairs

### ISSUE THREAD

**Issue by Stephenator0316** [scalda/FoolCraft#271] opened 2017-04-14 18:21 UTC
## SUGGESTION/HELP
- [] I would like to propose an additional mod, config change, custom recipe, etc.
- [] I am requesting help with installing or running the pack

## Issue Description
When I walk into chisels & bits stairs that I made or chiseled, I only automatically go up the first half of the block. The only way to go up is to jump or make the top half come down a pixel

## Reproduce Steps
Make a stair using chisels of bits that is modeled after vanilla stairs
Try to go up stairs. Fail

## Additional Information
Accoding to AlgorithmX2 (mod author) it's another mod that is doing this
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/260

**Comment by legodude17** [comment] 2017-04-14 18:29
I had trouble with this on vanilla stairs occasionally.

**Comment by Stephenator0316** [comment] 2017-04-16 20:06
Xisuma just found the issue

https://youtu.be/1j2xT80qi14?t=17m55s

**Comment by Jo-Mamma75** [comment] 2017-04-17 02:33
Likely a duplicate of #108 .

**Comment by scalda** [comment] 2017-04-22 16:06
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda

**Closed by scalda** 2017-04-22 16:06 UTC
Labels: bug, duplicate
