### ISSUE TITLE
World don't work!

### ISSUE THREAD

**Issue by Jaciii** [scalda/FoolCraft#846] opened 2017-11-07 15:19 UTC
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description

When I try to launch my Foolcraft world, it just says: "Loading world, Building terrain" like normal, but it continues to do that, and don't load the world. I have dedicated enough ram.

## Reproduce Steps

Log in to my Single player world.

## Additional Information

My very old backup works, but its to old, so I don't want to play that.

**Comment by BrisingrAerowing** [comment] 2017-11-07 23:28
Could you try again and post the game output? I am getting something similar while using a somewhat modified FC setup (some different / removed / added mods and related config / script changes), and the output indicates that LootTweaker is crashing, but I can't figure out what file is crashing. The only thing I know is that it happens when adding something to a loot table (determined from the stack trace).

**Comment by steamdemon1512** [comment] 2017-11-08 00:07
I had this issue with the Fluid Moos. I disabled the mod via the launcher, loaded the game, then closed and reactivated the mod to get it back. It tends to e caused by the pink slime moo

**Comment by Jaciii** [comment] 2017-11-08 06:59
My world don't crash, and I don't have a pink slime moo, but I can try to disable mini moos. The only way I can close minecraft when it happens, is to restart my computer.

**Comment by Jaciii** [comment] 2017-11-08 18:16
I still can't get into my world, but maybe I understood you wrong. What I did was 1. Open the Foolcraft folder. 2. find mini moos in the mod folder. 3. Rename the file to .jar.disabled insted of .jar 4. Launch the game and close it again. 5. change the filename back to .jar 6. Launch the game and it didn't work.

**Comment by RicardoTheCoder** [comment] 2017-11-11 11:42
@Jaciii Mini Moos should not present any problem like this, at least not in the most recent versions, which is already in FC 2.5.1. And most errors like that were generated when Moo Fluids was still present to convert the moos from a mod to the other.

It seems like your world might have some data that it's not in use anymore and causes problems.

@BrisingrAerowing Your problem can be easily fixed, looking at your log I can see that the problem occurs either in the **04-Loot-village_blacksmith.zs** or on the file that is loaded next (they should be loaded based on their order inside the scripts folder).

Check those files you might be adding loot from a mod or item you don't have anymore and that is what is causing the problem.

The general problem when loading world doesn't pass the loading screen it means that a mod crashed trying to complete a WorldLoadEvent or a similar event, you should check your log and try to find the crash there as minecraft might not show it to you.

Crashing in a WorldLoadEvent makes the game go into an infinite loop that will stay there till the user forcibly closes the game, so check your logs, and post them here to see if me or someone else can help out.

**Comment by BrisingrAerowing** [comment] 2017-11-11 17:48
@RicardoTheCoder I ended up figuring out my issue was a derp on my part. I had ported the scripts to 1.12.2 previously, and ended up doing a change needed for that version in 1.10 by accident. Reverting that change fixed the issue.

**Comment by Jaciii** [comment] 2017-11-12 06:39
I don't play with modern warfare, because its too buggy, so maybe its some files from that mod?

**Comment by RicardoTheCoder** [comment] 2017-11-12 14:13
@Jaciii Most definitely, I removed modern warfare too and add some problems with loots, soo it might be that too.

**Comment by Jaciii** [comment] 2017-11-12 17:51
What do you mean by be that too?

**Comment by Jaciii** [comment] 2017-11-13 17:19
My creative test world don't work too, and the last thing I did was to design a cloud with flat colored blocks and clear glass from TConstruct. I started to make the materials in my survival world. In the process to do that I incresed the size of the of my smeltery. After doing that the worlds don't work.

**Comment by scalda** [comment] 2017-11-13 17:26
Can you upload the world somewhere so I can see in person

**Comment by Jaciii** [comment] 2017-11-14 15:23
Here is my world files https://github.com/Jaciii/Foolcraft_not_working_world

**Comment by scalda** [comment] 2017-11-14 15:30
thanks i am downloading now and i will let you know what i find

**Comment by Jaciii** [comment] 2017-11-15 13:35
Maybe it's some thing to do with better questing, cause I tryed to use some commands from better questing?

**Comment by scalda** [comment] 2017-12-11 11:27
@Jaciii did you get any further with this sorry i have been really busy of late

**Comment by scalda** [comment] 2018-01-08 15:26
not heard anything here for 27 days so will be closing

**Closed** 2018-01-08 15:26 UTC
Labels: REQ - help wanted
