### ISSUE TITLE
Flux Networks: New Mod Addition Idea

### ISSUE THREAD

**Issue by Cinnamonster** [scalda/FoolCraft#424] opened 2017-05-01 20:13 UTC
## SUGGESTION/HELP
- [x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I have found that sometimes, the need or want for wireless networks for energy is present. Current systems are expensive, and people often need to run cables everywhere in their base walls just to power all those cool machines. I have discovered a mod while playing on a different modpack. This mod is called Flux Networks. It's on Curse and is free to use in any modpack (it says so in the project page). It provides inexpensive ways to wirelessly transfer RF power, and it's use in the modpack would make many things easier.

## Reproduce Steps
1. Look in the mod items list for a cheap RF transfer device.
2. Not find one.

**Comment by legodude17** [comment] 2017-05-01 21:17
Duplicate of #413.

**Comment by CakeArmy** [comment] 2017-05-02 18:13
+1you can only transfer as fast as dimensional transceviers allow which is slow

**Closed** 2017-05-03 15:29 UTC
