### ISSUE TITLE
Every time I sleep, I get stuck in the sleeping POV and typing menu, any fixes?

### ISSUE THREAD

**Issue by Yofreaky** [scalda/FoolCraft#292] opened 2017-04-17 23:33 UTC
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

**Comment by Yofreaky** [comment] 2017-04-17 23:36
When this happens, every time I sleep, the only fix I've found is to close out of minecraft and restart it. However this is stopping me from sleeping at all because it always happens. I may or may not have a crash report because I've crashed a few times for unknown reasons but it's so slim it's not worth looking into.

**Comment by Jo-Mamma75** [comment] 2017-04-18 00:45
Try moving your bed away from walls and other obstructions.  If you continue to get stuck, type "/ftb kickme" from the chat bar.

**Comment by Poke1650** [comment] 2017-04-18 02:55
Maybe adding Bed Bug would be a good idea?

**Comment by Jo-Mamma75** [comment] 2017-04-19 04:36
I just didn't want to suggest adding anything to the pack as it would technically no longer be supported.  The issue is a known issue in Minecraft but sometimes can be resolved by moving the bed or obstructions.

**Comment by CakeArmy** [comment] 2017-04-19 04:49
I have tested some things. I have not seen this happen yet with a sleeping bag. If people still report issues, maybe delete bed recipe and make it the crafting recipe for the sleeping bag?

**Comment by Ravalli03** [comment] 2017-04-19 19:06
I have ran into this issue before, and have noticed if you are getting stuck almost 100% of the time and using kick me, restart the pack and it would clear it from happing for a while.

**Comment by ardaniel** [comment] 2017-04-19 20:07
I've done this with the sleeping bag, unfortunately (although I was near a wall at the time).

**Comment by scalda** [comment] 2017-04-20 08:08
solution here is to use /ftb kickme. this has been mentioned many times already on the github in the closed issues

Considering this closed as it has been answered and is a duplicate of many others

**Closed by scalda** 2017-04-20 08:08 UTC
Labels: help wanted
