### ISSUE TITLE
Modern warfare Issues and complaints

### ISSUE THREAD

**Issue by Syntasu** [scalda/FoolCraft#388] opened 2017-04-26 17:58 UTC
## SUGGESTION/HELP
- [ x] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description

Today I tried digging into the Modern Warfare mod and I found it really hard to use and it being riddled with bugs. So i have compiled a list of annoyances and bugs.

**Annoyances**
- There is no wiki for this mod nor the source code being available.
- The recipes in JEI do no show up and it's really unclear how to get going with this mod . (could be considered a bug).

**Bugs**
- Bauxite ore not spawning in the world. NOTE: I don't have evidence that the ore doesn't spawn. This is based on the server I play on, I have pretty much every resource except bauxite ore. Asked other players and they seems to not have it either. (so I came to this conclusion). If it does spawn, it is too rare to even get started with this mod.
- Silicon ore (of Modern Warfare Mod) same as above mentioned.
- Copper ore (of Modern Warfare Mod) same as above mentioned.
- Aluminium ingots from Thermal Foundation does not work in Modern warfare recipes (as replacement for Modern warfare Aluminium, which is not obtainable due bauxite ore not spawning).
- Same goes for the Copper ingot
- Same goes for the Silicon

In my mind this mod is completely broken and should be replaced or removed. But that decision is up to you guys ;)

Let me know if you have experienced the same with this particular mod.

## Reproduce Steps

Pretty straightforward I think.

**Comment by AirForce101HD** [comment] 2017-04-27 09:54
I am having issues in Foolcraft 1.3.2 with Modern Warfare not reloading guns.

**Comment by Maudslay** [comment] 2017-04-27 13:57
I have also seen this issue where making the skins for weapons comes up as the nuggets that in the old version wasn't appearing and i second the motion where reloading guns in survival doesn't work as intended but in creative it does work for some reason. I've looked at the scripts that were newly added to the modpack have caused some of these issues.

**Comment by Syntasu** [comment] 2017-04-27 14:56
@AirForce101HD Because the default key is bound to R and is overwritten by other mods. Reassign it to another button wil fix reloading weapons.

**Comment by AirForce101HD** [comment] 2017-04-27 19:58
Ammo seems to work but the some of the sniper scopes do not seem to work, the lens area is white but it still contains the crosshair.

**Comment by GothCartel** [comment] 2017-04-30 06:06
There is an issue with guns not reloading, its not a keybind issue but more of the fact when you craft certain weapons especially shotguns its almost as if they are in a state where they cannot be loaded. To fix it you need to be in creative load the guns and then when back in survival they work fine. tested this on all shotguns and the scar L. handguns and rifles seem fine

**Comment by GothCartel** [comment] 2017-04-30 06:07
oh as for the ore spawn as well.. none of the modern warfare ores spawn on my server, even tp'd out 50k blocks to ensure of new world gen and it wasn't spawning there even after strip mining with veinminer for 500 blocks

**Comment by scalda** [comment] 2017-06-08 08:07
all these issues have been fixed in the latest mod release, if you find any more please make a new issue

**Closed by scalda** 2017-06-08 08:07 UTC
