### ISSUE TITLE
Shift-clicking items to add them to a resonator crashes the game if done fast enough

### ISSUE THREAD

**Issue by Jupisoft111** [scalda/FoolCraft#482] opened 2017-05-20 02:14 UTC
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
When I try to make more speed upgrades, I add a half stack or so of gold pressure plates in the resonator, and when I shift-click some more in my inventory to move them to the resonator, the creation progress in the resonator restarts, and if I shift-click several times fast enough, it crashes the game.

## Reproduce Steps
Keep shift-clicking a lot with gold pressure plates while the resonator is making upgrade bases.

## Additional Information
If you use it with care nothing bad should happen, but as it was taking so long to make the upgrades, I started shift-clicking fast enough to crash my game by the looks of it.

**Comment by FeikoJoosten** [comment] 2017-05-20 09:51
You probably want to close this issue and post it here. https://github.com/rwtema/extrautilities/issues 

The issue is related to extra utils 2 so please post it on the right page.

**Comment by scalda** [comment] 2017-05-29 17:45
What FeikoJoosten said

**Closed by scalda** 2017-05-29 17:45 UTC
