### ISSUE TITLE
Update from 1.33 to 1.47 crash on startup

### ISSUE THREAD

**Issue by ValkyrieWings** [scalda/FoolCraft#590] opened 2017-07-05 05:39 UTC
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I updated from 1.33 to 1.47
I have one Survival world and a separate Creative test world using the same seed both created in 1.33

Survival world crashes at load with the error "Ticking block entity"
    Mods heavily used: Chickens, Hatchery, Malisis doors, Botania, Chiselsnbits, Chisel, Ender IO, Refined 
    storage

Creative Test world does not crash but has major lag (more lag time than play time, making the game unplayable)
     Mods heavily used: Botania, Chiselsnbits

Creative world created after 1.47 update using same seed as the two above
    coordinates used in above 2 worlds does not have the same biome, Lag is again making the game 
    unplayable

I would like to keep the Survival and Test worlds as I've created a ton of custom chisel n bits structures in a biome I quite enjoy. any help would be appreciated.

## Additional Information
https://pastebin.com/35NzSxz0

**Comment by chland** [comment] 2017-07-05 11:39
The crash looks like a duplicate of https://github.com/scalda/FoolCraft/issues/589

Regarding the lag: did you use concrete from the concrete-mod? There seem to be a few problems with it.

**Comment by ValkyrieWings** [comment] 2017-07-06 01:02
No, I have not used concrete from the concrete mod. I'm using mostly
chiselsnbits, chickens, hatchery and Botania pretty much in that order

Julie Marshall

**Comment by Flekrad** [comment] 2017-07-08 00:32
I had the "Ticking block entity" error re chickens when I updated , try in a  1.33 world then putting all chickens in (nets) in a chest and then running it in 1.47 . If you you any Aluminium chickens "Dont" release them rebreed them from parents Not eggs  , they seemed to cause extra problems for me . Hope this helps

**Comment by ValkyrieWings** [comment] 2017-07-08 00:35
Thank you! I'll try that.

Julie Marshall

**Comment by Flekrad** [comment] 2017-07-08 04:04
To add the constantan chickens could also be the 1's I had issues with as well,, forgot to add this earlier

**Closed** 2017-08-22 12:06 UTC
