### ISSUE TITLE
Thermal Expansion Issues

### ISSUE THREAD

**Issue by Atm2222** [scalda/FoolCraft#219] opened 2017-04-09 03:44 UTC
Currently, there are no recipes in JEI for what can be made using TE machines. Plus, there is no recipe for invar plates, which makes me unable to make the flux anodizers augment.

**Comment by Cat09** [comment] 2017-04-10 03:05
after reporting a missing recepie, you can make a temporary fix for yourself by using a command that adds a minetweaker entry, I believe it is "/minetweakerrecepiecreator"? it may only support crafting tables though, not sure.

**Comment by Jo-Mamma75** [comment] 2017-04-12 20:06
We will look into it.  Thanks for reporting the issue.

**Comment by scalda** [comment] 2017-04-12 20:46
Is this via a server or in a single player world?

**Comment by Jo-Mamma75** [comment] 2017-04-12 20:59
Tested in 1.2.2 and it works fine in single player but there are issues with JEI recipes not synchronizing properly to the client on a server.  This will hopefully be resolved in 1.3 or 1.4.

**Comment by CakeArmy** [comment] 2017-04-15 05:17
Use a ftb client reload or a minetweaker reload. Should update recipies. Along with this, sag milling / pulverizing wood does not work. Not sure if this was intended? @Jo-Mamma75

**Comment by scalda** [comment] 2017-04-22 16:05
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda

**Closed by scalda** 2017-04-22 16:05 UTC
Labels: bug, priority-High
