### ISSUE TITLE
Neutronium Collector Bug (NOT DUPE BUG)

### ISSUE THREAD

**Issue by CakeArmy** [scalda/FoolCraft#491] opened 2017-05-20 21:30 UTC
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I am trying to use EnderIO conduits to extract the ingots from the collectors but it doesn't want to, I tried inserting into: drawer, drawer controller, compacting drawer, vanilla chest. Is this a config issue? I am on version 1.3.2 because I do not want the changes in 1.3.3 none of which affect this mod (as far as I can tell)

**Comment by FeikoJoosten** [comment] 2017-05-21 07:30
According to a wiki. You need to either extract it manually or using a pipe/item duct. https://ftbwiki.org/Neutron_Collector 

You could try using the transfer node from Extra Utils 2. 

Anyway, since this is not a foolcraft related issue, but more an issue related to compatibility it would be nice to put this on the issue github for either Ender I/O or Avaritia. 

Feel free to close this ;)

**Comment by CakeArmy** [comment] 2017-05-21 15:58
The reason I put it here was because it works in other modpacks. This made
me believe it might have been intentional?

**Comment by CakeArmy** [comment] 2017-05-21 16:43
I tried transfer nodes - do not work.

**Comment by FeikoJoosten** [comment] 2017-05-21 19:41
I disregard the comment on putting it on the wrong github page then (: 

> The reason I put it here was because it works in other modpacks. This made
me believe it might have been intentional?

You'll probably have to wait for a reply of a real admin of the modpack then. Sorry can't help you out any further ):
> I tried transfer nodes - do not work.

**Comment by scalda** [comment] 2017-05-28 07:57
It is nothing intentional by us. it is beeing looked into.

**Comment by scalda** [comment] 2017-06-08 10:38
This has been fixed in the latest version of the mod but sadly we can't update to it as avarita additions haven't been updated yet but as soon as it is both mods will be updated

**Comment by RubikMonat** [comment] 2017-06-15 00:18
Confirmed in 1.3.2 Tried extra utils transfer nodes, both the pushing one and the pulling one and they didnt work. Also put a vanilla hopper under one and it filled all 5 slots with one phantom item each, the inventory slot in the neutron collector displayed a red 0 next to it and the block had to be broken and re-placed to clear the red 0 after removing the hopper.

**Comment by CakeArmy** [comment] 2017-06-15 00:20
Yeah there is a dupe bug similar to what you are stating...

**Comment by scalda** [comment] 2017-06-16 09:37
Yes this is a issue with the current version of the avarita mod we have in the pack, we are waiting for avarita additions to update to be able to update the main mod

**Comment by Flekrad** [comment] 2017-07-08 11:29
The refined storage Importers collect the "pile of neutrons" which can then be crafted into nuggets and then ingots with no issues

**Closed** 2017-08-22 13:03 UTC
Labels: bug, NOP - awaiting mod update
