### ISSUE TITLE
Hermitron Fatal Error

### ISSUE THREAD

**Issue by Omegapsychosis** [scalda/FoolCraft#67] opened 2017-03-24 02:48 UTC
I recently experienced an issue where completing a set of hermitrons on a server (Rupert, node 3 of Iskall85's server) causes you to get a fatal error and get kicked from the server. I was able to reproduce the issue each time I clicked complete on the pedestal. No crash log as neither the client, nor server crashes.

This currently makes it impossible to complete hermitron tribes on a server.

**Comment by scalda** [comment] 2017-03-24 10:09
we have a update that needs applying to the pack but i am waiting on a few other things before i can get the pack out

**Comment by scalda** [comment] 2017-03-29 18:47
Does this work fine now since the update?

**Comment by Omegapsychosis** [comment] 2017-03-30 12:25
So far no, I have still not been able to click complete without getting disconnected from the server.

**Comment by scalda** [comment] 2017-03-31 10:05
Ok i have assigned the mod dev to this to look at it

**Comment by WinterGrave** [comment] 2017-03-31 16:12
Can't reproduce the issue, have tried on different servers and works fine. Any logs?

**Comment by Omegapsychosis** [comment] 2017-04-03 00:23
No logs, it happens on all 3 of Iskall's Patreon servers currently (Venus, Herkules, and Rupert). Placing all 9 hermitrons from a set in the pedestal is fine, but as soon as you click the button to complete the set it kicks you and only you from the server, the set is not completed upon logging back in and no crash reports are created.

**Comment by WinterGrave** [comment] 2017-04-03 15:42
What forge version is been used?

**Comment by Jo-Mamma75** [comment] 2017-04-09 18:21
Winter, the Forge version on the Patron servers is 2239.

**Comment by ftrocchi** [comment] 2017-05-23 22:20
Not sure why this is resolved.  It is still happening on version 1.3.3.  I can't complete a hermitron set.

**Comment by WinterGrave** [comment] 2017-05-24 15:12
I can't reproduce this error, I can successfully complete sets on my server using standard foolcraft pack from curse. I'd need a log to see where the error is so I can do something about it. Without a log, I can't find the cause.

**Comment by ftrocchi** [comment] 2017-05-24 15:54
Thanks WinterGrave.  I will see if I can get a log or two.

**Comment by scalda** [comment] 2017-06-08 08:06
This has now been fixed in the latest version thanks winter

**Closed by scalda** 2017-06-08 08:06 UTC
Labels: bug, resolved
