### ISSUE TITLE
The Game Crashed after creating a colossal chest

### ISSUE THREAD

**Issue by remco082000** [scalda/FoolCraft#154] opened 2017-03-31 22:26 UTC
The game crashed when i put the last block down. The colossal chest has one chest interface and the size was 3*3*3.
An similar crash happened in the SkyFactory 3 modack.

[crash-2017-03-31_23.39.14-client.txt](https://github.com/scalda/FoolCraft/files/887061/crash-2017-03-31_23.39.14-client.txt)

**Comment by scalda** [comment] 2017-04-01 05:58
did you make it hollow?

**Comment by Cat09** [comment] 2017-04-01 14:06
I had a crash on placing a chest interface into an incomplete giant chest, I think the mod itself is just a bit unstable. (Crainer & Ssundee's skyblock vids also show some unexpected behaviour with this mod)

**Comment by remco082000** [comment] 2017-04-01 17:59
To answer your question, scalda; yes, I made the chest hollow.

**Comment by cyrilrbt** [comment] 2017-04-03 16:07
For reference, I had a similar crash as well, in creative, using the diamond variety. I place a 3x3 ring of interfaces at the bottom, normal wall in the middle, the rest was just walls and a core, center block was empty. It crashed when I placed the last wall. The core was on the center on the middle layer.

**Comment by st3v1sh** [comment] 2017-04-04 21:42
I have weird interactions with colossal chests as well.. After building a 7x7x7 chest on FoolCraft version 1.2.1, my Grid Power is all bugged out with some giant numbers (~90000/1500.) Deleting the XU2SaveData.dat file doesn't help since this annoying bug seems to infect the entire modpack. Creating a new world still won't fix this, essentially making XU2 unusable.

**Comment by remco082000** [comment] 2017-04-07 18:26
So something I looked into may can solve this problem. When I start up my world, the mod Cyclops Core says it has an update that fixes Cube detection crashes. (Cyclops Core is a coremod for the Colossal Chests mod) If this mod gets updated it will hopefully fix this.

**Comment by scalda** [comment] 2017-04-22 15:53
Hi,

1.3 has just been released. Can you please retest this problem and if it still persists can you open a new issue using the template provided.

Regards

Scalda

**Closed by scalda** 2017-04-22 15:53 UTC

**Comment by remco082000** [comment] 2017-04-24 14:35
The problem seems to be fixed, thanks for your help!
Remco
