### ISSUE TITLE
Can not run game since 1.2.2 release

### ISSUE THREAD

**Issue by CBell74** [scalda/FoolCraft#202] opened 2017-04-07 04:51 UTC
I am not sure what is wrong - everything was fine until last update. Now i crash whenever I get to screen saying terrain downloading,  I am running at 6G.   Most recently I created april fool's pet and bone chicken and mechanical users - no sure if any of these would be cause
(Iskall's Dev Team are my heroes for developing this mod pack)

https://pastebin.com/X0q5rzya

**Comment by Jo-Mamma75** [comment] 2017-04-08 16:12
Duplicate of #208  - Please Close

It's a Mechanical User crash.
See https://github.com/scalda/FoolCraft/issues/208
I gave the other poster 3 options to resolve the issue.

**Closed** 2017-04-08 16:42 UTC
Labels: duplicate

**Comment by CBell74** [comment] 2017-04-08 18:51
I was able to fix with the disabling of MCA - Thank you so much, You guys are awesome at keeping up with issues!!
