### ISSUE TITLE
Withers don't drop stars

### ISSUE THREAD

**Issue by MCChiter** [scalda/FoolCraft#705] opened 2017-09-16 13:32 UTC
Killing wither with laser gun or katana from PlusTiC doesn't drop nether star
- [x] I am running the latest version of FoolCraft
- [x] I am running FoolCraft via Curse/Twitch Launcher
- [x] I can reproduce this issue consistently
     - [x] In single player
     - [x] In multiplayer
- [x] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.
- [ ] I am crashing and can provide my crash report(s)

## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I've killed five withers both using lasergun and katana, which do have infinity parts (which in this update became inaccessible as far as i know), both are linked to a chest, i tried breaking the link as well, which still doesn't help. every wither boss just dies without a single drop 

## Reproduce Steps
using laser or katana with infinity parts and linked to any chest kill a wither

## Additional Information
Update: killing wither just doesn't drop stars

**Comment by RicardoTheCoder** [comment] 2017-09-16 17:06
@MCChiter I had the same issue and I found a fix. However it only fixed the problem in single player.

@scalda This problem happens with both the Wither and the EnderDragon, the cause comes from EnderIO.

As EnderIO applies a pool to those loot tables and enforces a rolling to its pool the others will not be rolled, so no drops.

**How to fix it:** go to your client's folder, open the **scripts** folder and add to **04-Loot-entitiesbossdragon.zs** this line:
`dragon.removePool("Ender IO");`

And to the **04-Loot-entitiesbosswither.zs** this line:
`wither.removePool("Ender IO");`

In the server there might me something else changing the tables and preventing the tweaks to take full effect.

**Comment by janf3** [comment] 2017-09-16 17:29
I can't reproduce the issue in Foolcraft 2.1 SSP.
Using an Infinity Katana, even the Dragon Egg is placed in the linked inventory (tested with Vanilla chest and Iron chest). Wither Stars drop without any issues with both Global Traveler enabled and disabled.

I would try backing up your world and re-downloading the pack.

To the best of my knowledge EnderIO only changes Dungeon/Chest loot and Wither Skeleton head drop rates.

**Comment by RicardoTheCoder** [comment] 2017-09-16 17:40
@janf3 This problem happens to me both in SSP and in SMP, after applying the fix I mentioned above it fixed the problem for SSP. I can try with a fresh install and test it.

However about the EnderIO, when I use the **/mt loottables all** to dump all loot tables and check the Wither and EnderDragon loot table there is a pool called "Ender IO" in there as you can see in those two screenshots (those are without my fix).

![witherloottable](https://user-images.githubusercontent.com/13319775/30514531-51fe5e64-9b0e-11e7-8400-05a70f057bac.png)
![dragonloottable](https://user-images.githubusercontent.com/13319775/30514530-51fe5aa4-9b0e-11e7-9f66-8fd04ec619ae.png)

**Comment by janf3** [comment] 2017-09-16 18:27
@RicardoTheCoder 
I didn't check that, thanks for the information. But it shouldn't have that effect on the dropped loot. MC should go through all the pools in there.
It actually appears that EnderIO adds this empty pool to every single loot table, even chickens, squids or fishing. So if that was the cause _everything should be broken_.

**Comment by RicardoTheCoder** [comment] 2017-09-16 18:37
@janf3 I agreed with you, the minecraft code should read all those pools, but somehow it isn't reading them. It may also be because the Vanilla Minecraft does not contain a loot table for either the Wither or the EnderDragon (that can be checked in a vanilla 1.10.2 jar file)

For some strange reason applying my fix does the job when it comes to the Overworld (it is even stranger that it doesn't work on the Nether). Removing EnderIO solves the issue all around.

I think that it happens because those Loot Tables for both the Wither and the EnderDragon are manipulated by EnderIO, if you remove the scripts I mention in my first post, the tables are generated only with the EnderIO pool. If you remove EnderIO and leave the normal scripts (without the fix) everything works fine, they drop the items both in the Overworld and in the Nether (and of course the End in the case of the EnderDragon).

It is a very strange issue in my opinion, and might even be caused by multiple mods.

**Comment by MCChiter** [comment] 2017-09-16 18:46
Actually i never mentioned ender dragon here because battle went fine, though maybe i killed this flying lizard before the update so can't confirm that, thanks for the fix but i am the horrible abomination of mac gamers and applying this fix will be like writing Os Sierra without bugs.

**Comment by janf3** [comment] 2017-09-16 19:01
@MCChiter 

In the Twitch App right-click (control-click) FoolCraft and select _Open Folder_.
Or just use the finder to navigate to the files
`/Users/yourname/Documents/Curse/Minecraft/instances/FoolCraft/scripts`


The files are called `04-Loot-entitiesbosswither.zs` and `04-Loot-entitiesbossdragn.zs` and can be opened and modified using TextEdit.

**Comment by RicardoTheCoder** [comment] 2017-09-19 14:21
Apparently, my fix actually fixes the problem in all dimensions, I had a server-side mod conflicting with it, with a clean install and this fix it seems to drop everywhere.

For future reference, the problem with the drops in the Nether or End was a mod called "SpongeForge" I added to the server, to prevent the "move too quickly" error. After removing it my fix seems to work in all dimensions.

**Comment by Twan23** [comment] 2017-09-26 09:02
The wither doesn't drop any lootbag when killed by woot, what can I do to fix that?

**Comment by tehnomaag** [comment] 2017-10-02 06:38
@RicardoTheCoder fixes didn't work for me in singleplayer. Killed wither in overworld (with tinkers sword) and still no drops.

FoolCraft version 2.1. I think instance and world was also created in 2.1.

**Comment by RicardoTheCoder** [comment] 2017-10-02 09:54
@Twan23 That is a thing with the woot configuration, I would say it is intentional but I could be wrong, you could try and play around with the woot config and see if you can get it dropping for you. Though I would say you should backup everything first and understand that those changes might not get into the pack, however, you could always make a suggestion ;)

@tehnomaag As I came to find out, it seems that there is also another error happening. With my fix, they start dropping but sometimes there is an error with the loot bags and because of that nothing drops. My fix seems to only fix half of the problem. For me, the loot bag error happened a series of times in a row till it dropped something. (Sometimes it even caused a crash)

Try commenting the loot bag drops from the wither script and try again, see if that fixes the problem for you.

**Comment by scalda** [comment] 2017-10-02 10:06
this is fixed in the next version, i am working on it now

**Closed** 2017-10-02 10:30 UTC

**Comment by tehnomaag** [comment] 2017-10-03 08:49
Confirmed, killing Wither with same weapon as before dropped nether star and Stressmonster loot bag in 2.2 now for me. Thanks.
