### ISSUE TITLE
FPS Drop While Holding Or looking at Ender lilly - Dont make a farm with those plants

### ISSUE THREAD

**Issue by johnwolf01** [scalda/FoolCraft#854] opened 2017-11-11 10:15 UTC
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
Started a new world in 2.4 Update, - Updated to the 2.5.1 and since then I am getting sudden game lag with my ram spiking constantly without stopping and a frame drop from 80fps to 5fps, almost  suggesting a ticking loop error or something trying to load or spawn but fails and repeats. Only option to get frames back is to Quit, Restart Pc and reload. Sad part is 15-20min into playing, lag is back.

Since It is a brand new world created and no Tech crafted yet only done some resource gathering .
I dont understand the cause ,. And it is in the End Dimension - where I was planning to build my base.

I do enjoy the teleporting Creepers though ... (-.-)

**Comment by johnwolf01** [comment] 2017-11-11 11:13
Found What I think the issue is. Whenever I am holding and ender lilly seed in my hand my frames crash.
I assume it has some rendering issue.

**Comment by RicardoTheCoder** [comment] 2017-11-11 11:53
@johnwolf01 Lets test something to see if the problem is really related to Ender Lillies, create a new single player world in creative, get an end stone and an ender Lilly, place it on the end stone (do this in the overworld), and look at it.

If the lag hits, then that is the problem and can be fixed by disabling the ender lilies otherwise you might have a different issue that impacts ender lilies but it's not caused by it.

Also, teleporting creepers are the most amusing of them all :P. they are mostly harmless as you will come to find, just try not being knocked out of the island xD

**Comment by johnwolf01** [comment] 2017-11-11 19:35
@RicardoTheCoder 
Well I have done something similar to what you were saying. 
As hinted to above I went to a new unexplored area in the end where there just so happen to be a single ender lilly on one of those very small bubble like Endstone islands (9x9 ish).. when my cursor ponts to the lilly my frames drop.

when I break the lilly plant and get the seed (and pearl) frames go back to normal If im not holding the seed in my main hand. When I hold the seed in my main hand to plant it. The frames drop to 3-5 fps.

I managed to remove most of the seeds from the main area Im playing / building in.
Thankyou kindly

**Closed** 2017-11-12 06:00 UTC

**Comment by GWSheridan** [comment] 2017-11-16 00:21
Also get this bug 100% extra Utilities installed the mod on its own with out any other mod cheated in a enderlilly seed FPS drops holding it an seeing it on the ground. also the same is with the Redorchid FPS goes from 800fps down to 12fps. This only happens in version 1.6.5 of Extra Utilities. Dropped down a version to 1.6.4 there is no problem with the seeds
