### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by MPHBEST** [scalda/FoolCraft#358] opened 2017-04-24 17:36 UTC
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [x] I am requesting help with installing or running the pack

## Issue Description 
When i start up FoolCraft it gets to load and then the game just crashes.

## Reproduce Steps 
1. Start minecraft launcher
2. Run game
3. Get to loading
4. Crash

## Additional Information
I'm using 6gb allocated ram
Crash log:https://pastebin.com/fWL43JZ8
Well minecraft window can become full white or just get stuck
I can load for longer if i only load and dont do anything else on my pc
I have a factory install of FoolCraft

**Comment by JerichoTitan** [comment] 2017-04-24 18:10
I am having the same problem as well

**Comment by MPHBEST** [comment] 2017-04-24 18:16
Well now we know it isnt just me

**Comment by scalda** [comment] 2017-04-24 18:40
need crash reports please not the game logs

**Comment by MPHBEST** [comment] 2017-04-24 18:49
oh im just dumb then
i didnt realize

**Comment by MPHBEST** [comment] 2017-04-24 18:50
ill try to see if i can get a crash report

**Comment by scalda** [comment] 2017-04-24 18:53
ok thanks

**Comment by MPHBEST** [comment] 2017-04-24 18:57
i dont think i can
i just tried doing it again stops loading and screen goes white no crash report just game output
there might be some location where crash reports are stored in, do you know

**Comment by MPHBEST** [comment] 2017-04-24 18:59
also something about 1.3 for some reason i can load much farther than i could in 1.2.
Like in 1.2 the bar would only go halfway now it goes to full and stops at grandfather clock

**Comment by RADxUK** [comment] 2017-04-24 18:59
Hi, I'm getting the same issue. Tried clicking on View Crash Report from the launcher and it's not working. What it does tell me is this:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MalisisDoors (malisisdoors)

**Comment by scalda** [comment] 2017-04-24 19:01
you will have to go into the MC folder and access the crash report folder that way

**Comment by MPHBEST** [comment] 2017-04-24 19:01
for foolcraft?

**Comment by scalda** [comment] 2017-04-24 19:01
yes

**Comment by MPHBEST** [comment] 2017-04-24 19:01
there is none

**Comment by RADxUK** [comment] 2017-04-24 19:02
Hi Scalda, I have one, but I'm new to this...how do you want it?

**Comment by MPHBEST** [comment] 2017-04-24 19:02
send it thourgh pastebin

**Comment by MPHBEST** [comment] 2017-04-24 19:03
https://pastebin.com/

**Comment by MPHBEST** [comment] 2017-04-24 19:03
maybe remove malisis

**Comment by RADxUK** [comment] 2017-04-24 19:06
Scalda here you go - [https://pastebin.com/uDK30nFd](url)

**Comment by RADxUK** [comment] 2017-04-24 19:06
did that work?

**Comment by MPHBEST** [comment] 2017-04-24 19:07
no 404 error

**Comment by RADxUK** [comment] 2017-04-24 19:07
hmm

**Comment by MPHBEST** [comment] 2017-04-24 19:07
im gonna remove malisis and see if that fixes it

**Comment by MPHBEST** [comment] 2017-04-24 19:09
no the pastebin does work

**Comment by MPHBEST** [comment] 2017-04-24 19:09
but you have to copy and paste the link onto a new tab

**Comment by RADxUK** [comment] 2017-04-24 19:10
https://pastebin.com/uDK30nFd

**Comment by MPHBEST** [comment] 2017-04-24 19:11
you have optifine

**Comment by MPHBEST** [comment] 2017-04-24 19:11
reportedly doesnt work with enderio

**Comment by RADxUK** [comment] 2017-04-24 19:11
Yes, not had any problems with it

**Comment by MPHBEST** [comment] 2017-04-24 19:12
try removing optifine

**Comment by RADxUK** [comment] 2017-04-24 19:13
Thanks, I'll wait and see what Scalda says ;)

**Comment by MPHBEST** [comment] 2017-04-24 19:14
hmm it might be gpu drivers

**Comment by MPHBEST** [comment] 2017-04-24 19:15
my screen disconnects everytime its at 7/7 and then minecraft goes completly white

**Comment by MPHBEST** [comment] 2017-04-24 19:16
now to remember where i have my driver thingy majib

**Comment by JerichoTitan** [comment] 2017-04-24 19:24
Ok, correction my game crashes after I have opened up my current foolcraft world

**Comment by JerichoTitan** [comment] 2017-04-24 19:25
[crash-2017-04-24_15.21.22-server.txt](https://github.com/scalda/FoolCraft/files/952871/crash-2017-04-24_15.21.22-server.txt)
here is my crash report

**Comment by scalda** [comment] 2017-04-24 19:26
What version of the pack are you useing?

**Comment by JerichoTitan** [comment] 2017-04-24 19:27
1.2

**Comment by MPHBEST** [comment] 2017-04-24 19:27
it seems like it wasnt my drivers

**Comment by JerichoTitan** [comment] 2017-04-24 19:27
I can't use 1.3.2 because of this
<img width="611" alt="screen shot 2017-04-24 at 3 10 31 pm" src="https://cloud.githubusercontent.com/assets/19862010/25354848/96289006-2902-11e7-9279-4b85e86adb0a.png">

**Comment by MPHBEST** [comment] 2017-04-24 19:28
something else is not letting me play

**Comment by scalda** [comment] 2017-04-24 19:29
ok @JerichoTitan the crash is a mech user from ExU2 this is the reason why we have disabled them in 1.3.2

**Comment by JerichoTitan** [comment] 2017-04-24 19:31
I knew that but I have no idea addon install error is happening

**Comment by RADxUK** [comment] 2017-04-24 19:38
@JerichoTitan That happened to me and I restarted the Twitch tool. Which cleared that issue. It then downloaded the update. But it then crashes mid loading.

**Comment by RADxUK** [comment] 2017-04-24 19:49
@scalda I removed optifine and that resolved my issue

**Comment by JerichoTitan** [comment] 2017-04-24 20:00
My issue has been resolved by simply updating and restarting

**Comment by MPHBEST** [comment] 2017-04-24 20:04
My issue is still prevelant

**Comment by MPHBEST** [comment] 2017-04-24 20:05
and i cant even get a crash report

**Comment by dragontearsn** [comment] 2017-04-25 00:28
I believe I am getting a similar crash as well (singleplayer and no optifine).  Game loads through forge and I can see a split second of notifications that load on the chat line - then crashes.  Notification appears but link to crash report does not work, but I found the folder for you.
https://pastebin.com/jNdxZa5n
Hopefully this helps but back to 1.2.2 until then.

**Comment by scalda** [comment] 2017-04-25 07:54
@dragontearsn remove googleeyes and reload the pack

**Comment by dragontearsn** [comment] 2017-04-25 12:49
Tried no googlyeyes and did not work on first try.  Not sure I got a clean reload of the pack with my terrible internet and I have to go to work so no time to troubleshoot right now, I will try later.  Just in case it might help:  https://pastebin.com/qFFVuQ7B    The crash report from this attempt.

**Comment by MPHBEST** [comment] 2017-04-25 19:47
Holy cow i seem to have fixed the issue

**Comment by MPHBEST** [comment] 2017-04-25 19:50
I goed to C:\Users\Hannu\Documents\Curse\Minecraft\Instances\FoolCraft\config\splash
and turned enabled to false
http://imgur.com/a/iplrU

**Comment by MPHBEST** [comment] 2017-04-25 19:52
@scalda

**Comment by Peachie123** [comment] 2017-04-26 17:16
My crash issue seems to be with the decocraft mod specifically. Anyone else found this?

**Comment by grannypatty** [comment] 2017-04-29 14:34
@scalda  hi I don't know if y'all have solved this yet...I don't know if it's the same for everyone but after chasing red herring's for the past 5 days..we were able to solve this on all of our active servers and single player worlds..in total after the 1.3 update we lost 9 servers and 17 single player worlds to the above mentioned error. We literally spent hours upon hours chasing this and we think we've been ble to confirm (at least on our end but like I said 26 different saves) We had no idea what the naturalpledge mod was thus we deleted it, some of us don't have as beefy of computers as others....but in every.  EVERY case.... natural pledge was the cause.. but to the exptent that we first didn't have botanaia on any of the above mentioned worlds...so when running our new updates..at first we ran into the naturalpledge was a dependent to botania. On the servers who already had botania removed it was a lot easier to diagnose once we got on the trail... so, if botania is deleted...and a instance tries to run w/o deleting naturalpledge it will tell you that your missing botania  and it can't run ..so you either would put botania back in or go back and delete natural pledge.. anyways we have tried it 9 different ways to Sunday and replicated it every time on every server and so world that had the error... idk if it's just a hiccup...or a heart attack...but we are up and running... the logs...crash reports were useless until we were' able to replicate problem.  We are ALL BACK UP AND RUNNING...I was asked to drop you a line here...this is obviously where we started at first too.... 
but ended up chasing a lot more red herrings than it was worth....lol... much respect Scalia. You are one in a million... we have a lot of peeps that look up to you! Your inspiration to my people...little they may be...much respect

**Closed** 2017-05-03 15:04 UTC
Labels: help wanted

**Comment by qwsxedcrfv** [comment] 2017-06-03 02:12
@grannypatty wait.. so just remove naturalpledge and botania? There's a lot of people who don't know about this and I'm trying to find a solution, so any clarification would be wonderful.
From Issue #330

**Comment by Clintis** [comment] 2017-07-10 18:45
I am having the same issue as well, Here is my pastebin
https://pastebin.com/3RMVYasd

**Comment by scalda** [comment] 2017-07-10 18:48
@Clintis remove optifine

**Comment by Starson182** [comment] 2017-08-21 17:10
I have the same problem and I have searched this entire page for the answer and for like about a week already. Here is my pastebin (crash report)
[https://pastebin.com/dZ5kqjDP](url)

**Comment by Marconium2** [comment] 2017-09-12 02:14
https://pastebin.com/8AbhHDbY
here is my pastebin for the crash report

**Comment by senna145** [comment] 2017-12-20 16:02
@scalda https://pastebin.com/mhuef6zr

**Comment by virtualadept** [comment] 2017-12-20 16:31
If your crash report has: 

java.lang.OutOfMemoryError: GC overhead limit exceeded

It means you need to allocate more ram via -Xmx

This pack needs at least 6 gigs of ram.  The last 3 pastebin crashes didnt have enough ram allocated.

**Comment by Jaron001** [comment] 2018-02-12 10:23
@scalda how do i allocate me ram

**Comment by scalda** [comment] 2018-02-12 12:15
there are plenty of guides on youtube or google sorry can't help any extra
