### ISSUE TITLE
Drums Cheat

### ISSUE THREAD

**Issue by ajdjyt** [scalda/FoolCraft#762] opened 2017-09-29 14:26 UTC
## SUGGESTION/HELP
- [X] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
You Can duplicate drums 
possibly getting unlimited iron

## Reproduce Steps
eg i have a stack of drums filled with a mb of crude oil, when i will go to clear it i can get 64 stacks of empty drums 

## Additional Information
Screenshots
![2017-09-19_16 11 28](https://user-images.githubusercontent.com/26516505/31020179-db2b2f00-a54f-11e7-8cd3-019b9aadbac2.png)
![2017-09-19_16 11 30](https://user-images.githubusercontent.com/26516505/31020178-db07f882-a54f-11e7-807b-ce7ccaedf56a.png)
![2017-09-19_16 11 31](https://user-images.githubusercontent.com/26516505/31020177-db03e468-a54f-11e7-929e-66d2244fe3ff.png)
![2017-09-19_16 11 18](https://user-images.githubusercontent.com/26516505/31020176-db039de6-a54f-11e7-83da-092ffca63aa7.png)
![2017-09-19_16 11 22](https://user-images.githubusercontent.com/26516505/31020180-db343924-a54f-11e7-9aaf-5df7764728d7.png)
![2017-09-19_16 11 24](https://user-images.githubusercontent.com/26516505/31020181-db3bac36-a54f-11e7-813b-a00d2270bccf.png)

**Comment by notmark** [comment] 2017-10-04 00:59
It looks like you have JEI cheat mode enabled.

**Comment by scalda** [comment] 2017-10-12 11:42
i can't reproduce this bug on 2.3.1 version of the pack sorry closing the issue

**Closed by scalda** 2017-10-12 11:42 UTC
