### ISSUE TITLE
Server crashes when connecting.

### ISSUE THREAD

**Issue by ponduzn** [scalda/FoolCraft#221] opened 2017-04-09 09:40 UTC
**Hello!**
I was making a fluid cow milking farm, then the server suddenly crashed, giving me this error:
"java.io.IOException: An existing connection was forcibly closed by the remote host"

Any way to fix this ? kinda bummed out

error log:
"[10:22:21] [Server thread/INFO]: ponduzn joined the game
[10:22:22] [Server thread/WARN]: Skipping Entity with id 
[10:22:22] [Server thread/WARN]: Skipping Entity with id 
[10:22:23] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.RuntimeException: Error while interacting with block minecraft:air with null. Method:ENTITY Button:RIGHT_CLICK
at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:289) ~[TileUse.class:?]
at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:93) ~[TileAdvInteractor.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) ~[ls.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
... 4 more
Caused by: java.lang.NullPointerException
at mca.packets.PacketInteractWithPlayerC.<init>(PacketInteractWithPlayerC.java:41) ~[PacketInteractWithPlayerC.class:?]
at mca.core.forge.EventHooksForge.entityInteractEventHandler(EventHooksForge.java:221) ~[EventHooksForge.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_295_EventHooksForge_entityInteractEventHandler_EntityInteract.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
at net.minecraftforge.common.ForgeHooks.onInteractEntity(ForgeHooks.java:1008) ~[ForgeHooks.class:?]
at net.minecraft.entity.player.EntityPlayer.func_184822_a(EntityPlayer.java:1158) ~[zs.class:?]
at com.rwtema.extrautils2.compatibility.CompatHelper.interactOn(CompatHelper.java:72) ~[CompatHelper.class:?]
at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:280) ~[TileUse.class:?]
at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:93) ~[TileAdvInteractor.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) ~[ls.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
... 4 more"

Crash report:
[crash-2017-04-09_10.22.23-server.txt](https://github.com/scalda/FoolCraft/files/908099/crash-2017-04-09_10.22.23-server.txt)

**Comment by ponduzn** [comment] 2017-04-09 10:23
I managed to bypass this issue with MCedit, removed the mechanical users that was placed, and could now log back in. 
Hope you fix this issue asap!
Thank you.

**Comment by Jo-Mamma75** [comment] 2017-04-13 15:45
Duplicate of #239

**Closed by Jo-Mamma75** 2017-04-13 15:45 UTC
Labels: duplicate
