### ISSUE TITLE
Blitz, Blizz and Basalz seeds incompatible with agricraft cropsticks

### ISSUE THREAD

**Issue by enmac** [scalda/FoolCraft#210] opened 2017-04-08 04:16 UTC
Was playing around in creative, noticed these mystical agriculture seeds (Blizz/Blitz/Basalz) are incompatible with agricraft - cannot be planted using crop sticks, no growth options to get them to 10/10/10 ;)

**Comment by CriticalMole** [comment] 2017-04-08 11:14
Fixed in 1.3

**Comment by Jo-Mamma75** [comment] 2017-04-11 00:25
Duplicate of [https://github.com/scalda/FoolCraft/issues/132](url)
Leave open until v1.3 is released to public.

**Closed** 2017-04-22 15:31 UTC
Labels: duplicate, resolved
