### ISSUE TITLE
mechanical user causes crash when placing bucket inside.  Player can no longer join server until block removed

### ISSUE THREAD

**Issue by mummsword** [scalda/FoolCraft#269] opened 2017-04-14 13:52 UTC
## SUGGESTION/HELP
- [] I would like to propose an additional mod, config change, custom recipe, etc.
- [] I am requesting help with installing or running the pack

**Comment by mummsword** [comment] 2017-04-14 13:54
I am playing multiplayer, running latest version of FoolCraft.  I have reproduced this issue not consistently but crashed server twice and had to have server host remove block.  I can provide crash report.

**Comment by ALeaSilverleaf** [comment] 2017-04-14 15:32
I can repeat it reliably both in single and multi. I am playing latest version. My crash was not placing into a bucket into a mech user, it was hooking the conduit to system. My work around was changing to a colossal chest that all inputs went into. And that seemed to fix the issue. When mine crashed I couldn't even get back into the world. It was a complete fail and I had to restart. I will try to find the crash reports in my computer.

**Comment by TheonlyTazz** [comment] 2017-04-14 17:04
you guys clearly didnt do 
[] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I'm having the same problem.

because:
https://github.com/scalda/FoolCraft/issues/239

**Comment by legodude17** [comment] 2017-04-14 17:12
@TheonlyTazz What makes you so sure that they didn't do that. Also, it wasn't really fixed, just gave a workaround and then closed.

**Comment by Cat09** [comment] 2017-04-14 17:24
this is a known bug with extra utilities 2, it appears to happen when it tries to use an invalid item on a player, this issue is a duplicate of several closed issues. I wonder about having one of these stickied on here so people don't feel the need to keep posting?

**Comment by legodude17** [comment] 2017-04-14 18:17
That seems like a good idea.

**Comment by TheonlyTazz** [comment] 2017-04-14 18:17
thanks Cat09,

Legodude17, this is a known issue, which has been reported multiple times and also has been said that they are fixing it in 1.3

**Comment by legodude17** [comment] 2017-04-14 18:18
@TheonlyTazz where was that said?

**Comment by TheonlyTazz** [comment] 2017-04-14 18:18
https://github.com/scalda/FoolCraft/issues/167

**Comment by mummsword** [comment] 2017-04-14 18:34
Man some people are very rude and full of themselves!  Try a little courtesy!  I don't know how to search this thing!  I just know it needs fixed!

**Comment by TheonlyTazz** [comment] 2017-04-14 19:00
http://puu.sh/vkejE/4ac6750535.png

**Comment by CriticalMole** [comment] 2017-04-14 21:29
Duplicate of #167

**Closed by CriticalMole** 2017-04-14 21:29 UTC
Labels: duplicate
