### ISSUE TITLE
Hermitron Complete Set button kicks player out.

### ISSUE THREAD

**Issue by ftrocchi** [scalda/FoolCraft#494] opened 2017-05-23 22:25 UTC
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ ] I am requesting help with installing or running the pack

## Issue Description
I am on version 1.3.3.  I have all the hermitrons for Beta-8.  When I put them in and click Complete Set the game crashes.

## Reproduce Steps
This happens every time I try, but I so far only have the one set to test with.

## Additional Information
I show it happening in my YouTube video at 2:00 mark or so.  https://www.youtube.com/watch?v=jUb-p2zGRXE

**Comment by CakeArmy** [comment] 2017-05-24 00:17
Yeah, I have this problem. Never got around to reporting it as I figured they knew (I dont know how they can miss this, its been like this since release)

**Comment by WinterGrave** [comment] 2017-05-24 15:59
Ok this has been a problem for me to debug since I can't reproduce the error. What are you running the server on? What forge version? Any logs I can get?

**Comment by ftrocchi** [comment] 2017-05-24 16:08
Hi WinterGrave.

My server is hosted by CubedHost, and I am using their tools which automatically installed the server.  So it should be full standard for the version they have.  I would assume it is up to date.

In the logs on the server, when I click the button I am getting an exception of 'NoSuchMethodError'.

Here is a pastebin from when I logged in, clicked the button, and am booted.  
https://pastebin.com/qwx8x3dZ

Hope this helps.

**Comment by CakeArmy** [comment] 2017-05-25 03:57
I use "TheMinecraftHosting" ik name is odd but I dont care, cheap and have
good servers. I can also get a log.

**Comment by WinterGrave** [comment] 2017-05-25 23:48
@ftrocchi the server is trying to get the Client side player for some reason, I can't replicate the issue using the forge server on a windows machine but still investigating what is going on

**Comment by scalda** [comment] 2017-06-08 10:43
this has been fixed in the latest version. thanks for the report

**Closed by scalda** 2017-06-08 10:43 UTC
